### ISSUE TITLE
How Do I Skid This?

### ISSUE THREAD

**Issue by SmileMan1235** [ChompChompDead/Teddyware-Client#11]
so basically idk how i skid never done it before and idk java i just wanna skid a fat poopy client then watch some youtube tutorial and paste that code somewhere in a .lua file cus clients are made in lua so pls tell me how to skid im having so much trouble with this lua stuf

**Comment by PeterPePem** [comment]
Bro, Minecraft clients are made in java LOL

**Comment by PeterPePem** [comment]
Omg

**Comment by SmileMan1235** [comment]
@PeterPePem but i watched a tutorial and it said its made in python

**Comment by PeterPePem** [comment]
Who said this is a liter lol

**Comment by PeterPePem** [comment]
Usually, Minecraft clients are 100% in java

**Comment by SmileMan1235** [comment]
i watched a roblox tutorial on how to make clients for minecraft but it not work and the guy said its in javascript

**Comment by PeterPePem** [comment]
Just with some exceptions but usually they are 100% coded in java

**Comment by SmileMan1235** [comment]
nah im sure its in ruby

**Comment by PeterPePem** [comment]
> i watched a roblox tutorial on how to make clients for minecraft but it not work and the guy said its in javascript

U are joking, right?

**Comment by SmileMan1235** [comment]
no

**Comment by SmileMan1235** [comment]
if i was i would be going "haha funny xd lol"

**Comment by hng12** [comment]
visit https://skiddyskidskid.skid

**Comment by wendellmeset** [comment]
lol

**Comment by wendellmeset** [comment]
This is sad, 1. you used a ROBLOX tutorial to make minecraft client when it clearly is for ROBLOX
and 2. also its pretty impossible to make minecraft client (which is a minecraft mod) in lua, because minecraft mods only work if they are written in java, if you wanna know how to skid ask me, contact me on discord Sherlock Holmes#0997 
@SmileMan1235

**Comment by ChompChompDead** [comment]
Fart most often refers to: Flatulence, the act of expelling intestinal gas through the anus.

**Comment by timo-zzz** [comment]
smile was joking you incels

**Comment by ChompChompDead** [comment]
he wasnt joking, ii. please shut up

**Comment by Officer32k** [comment]
@PeterPePem maybe because java is the only language u can make anything in minecraft
