### ISSUE TITLE
burrow doesent even work, it starts rubberbanding you as soon as you burrow

### ISSUE THREAD

**Issue by Pexku789** [ChompChompDead/Teddyware-Client#8]
nig

**Comment by Crystallinqq** [comment]
paste issue. issue closed.

**Comment by ChompChompDead** [comment]
Ill fix that

**Comment by timo-zzz** [comment]
what server u on? does it have burrow patched?

**Comment by SmileMan1235** [comment]
Yeah I Like ASS
After
School
Snacks

**Comment by Pexku789** [comment]
lmao doesnt work on any basic server you would play on

**Comment by ChompChompDead** [comment]
it does for me

**Comment by Pexku789** [comment]
like on what servers

**Comment by ChompChompDead** [comment]
i know it works on allahowns.me but it works best inside holes

**Comment by Pexku789** [comment]
ok nn server, try it on cc or 9b

**Comment by ChompChompDead** [comment]
ok. join the discord for more help, this thread is too long https://discord.gg/X2BmAqW8ry

**Comment by Crystallinqq** [comment]
This is not a thread it is a issue stfu

**Comment by SmileMan1235** [comment]
@Crystallinqq stfu your mother ez

**Comment by Pexku789** [comment]
ez

**Comment by Crystallinqq** [comment]
@SmileMan1235 lol

**Comment by SmileMan1235** [comment]
@Crystallinqq do you like poop

**Comment by SmileMan1235** [comment]
guys i am on discord but github @everyone i pinged everyone 😱

**Comment by Officer32k** [comment]
this is fucking retarded
